// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: department_service.proto

package department

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DepartmentService_Save_FullMethodName                   = "/department.service.v1.DepartmentService/Save"
	DepartmentService_Read_FullMethodName                   = "/department.service.v1.DepartmentService/Read"
	DepartmentService_List_FullMethodName                   = "/department.service.v1.DepartmentService/List"
	DepartmentService_DeleteDepartment_FullMethodName       = "/department.service.v1.DepartmentService/DeleteDepartment"
	DepartmentService_DepartmentMemberList_FullMethodName   = "/department.service.v1.DepartmentService/DepartmentMemberList"
	DepartmentService_SearchDepartmentMember_FullMethodName = "/department.service.v1.DepartmentService/SearchDepartmentMember"
	DepartmentService_InviteDepartmentMember_FullMethodName = "/department.service.v1.DepartmentService/InviteDepartmentMember"
	DepartmentService_RemoveDepartmentMember_FullMethodName = "/department.service.v1.DepartmentService/RemoveDepartmentMember"
	DepartmentService_DepartmentMemberDetail_FullMethodName = "/department.service.v1.DepartmentService/DepartmentMemberDetail"
)

// DepartmentServiceClient is the client API for DepartmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepartmentServiceClient interface {
	Save(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DepartmentMessage, error)
	Read(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DepartmentMessage, error)
	List(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*ListDepartmentMessage, error)
	DeleteDepartment(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DeleteDepartmentResponse, error)
	DepartmentMemberList(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DepartmentMemberListResponse, error)
	SearchDepartmentMember(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DepartmentMemberListResponse, error)
	InviteDepartmentMember(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*InviteDepartmentMemberResponse, error)
	RemoveDepartmentMember(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*RemoveDepartmentMemberResponse, error)
	DepartmentMemberDetail(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DepartmentMemberDetailResponse, error)
}

type departmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepartmentServiceClient(cc grpc.ClientConnInterface) DepartmentServiceClient {
	return &departmentServiceClient{cc}
}

func (c *departmentServiceClient) Save(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DepartmentMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepartmentMessage)
	err := c.cc.Invoke(ctx, DepartmentService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentServiceClient) Read(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DepartmentMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepartmentMessage)
	err := c.cc.Invoke(ctx, DepartmentService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentServiceClient) List(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*ListDepartmentMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDepartmentMessage)
	err := c.cc.Invoke(ctx, DepartmentService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentServiceClient) DeleteDepartment(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DeleteDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDepartmentResponse)
	err := c.cc.Invoke(ctx, DepartmentService_DeleteDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentServiceClient) DepartmentMemberList(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DepartmentMemberListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepartmentMemberListResponse)
	err := c.cc.Invoke(ctx, DepartmentService_DepartmentMemberList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentServiceClient) SearchDepartmentMember(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DepartmentMemberListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepartmentMemberListResponse)
	err := c.cc.Invoke(ctx, DepartmentService_SearchDepartmentMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentServiceClient) InviteDepartmentMember(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*InviteDepartmentMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteDepartmentMemberResponse)
	err := c.cc.Invoke(ctx, DepartmentService_InviteDepartmentMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentServiceClient) RemoveDepartmentMember(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*RemoveDepartmentMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveDepartmentMemberResponse)
	err := c.cc.Invoke(ctx, DepartmentService_RemoveDepartmentMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentServiceClient) DepartmentMemberDetail(ctx context.Context, in *DepartmentReqMessage, opts ...grpc.CallOption) (*DepartmentMemberDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepartmentMemberDetailResponse)
	err := c.cc.Invoke(ctx, DepartmentService_DepartmentMemberDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepartmentServiceServer is the server API for DepartmentService service.
// All implementations must embed UnimplementedDepartmentServiceServer
// for forward compatibility.
type DepartmentServiceServer interface {
	Save(context.Context, *DepartmentReqMessage) (*DepartmentMessage, error)
	Read(context.Context, *DepartmentReqMessage) (*DepartmentMessage, error)
	List(context.Context, *DepartmentReqMessage) (*ListDepartmentMessage, error)
	DeleteDepartment(context.Context, *DepartmentReqMessage) (*DeleteDepartmentResponse, error)
	DepartmentMemberList(context.Context, *DepartmentReqMessage) (*DepartmentMemberListResponse, error)
	SearchDepartmentMember(context.Context, *DepartmentReqMessage) (*DepartmentMemberListResponse, error)
	InviteDepartmentMember(context.Context, *DepartmentReqMessage) (*InviteDepartmentMemberResponse, error)
	RemoveDepartmentMember(context.Context, *DepartmentReqMessage) (*RemoveDepartmentMemberResponse, error)
	DepartmentMemberDetail(context.Context, *DepartmentReqMessage) (*DepartmentMemberDetailResponse, error)
	mustEmbedUnimplementedDepartmentServiceServer()
}

// UnimplementedDepartmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDepartmentServiceServer struct{}

func (UnimplementedDepartmentServiceServer) Save(context.Context, *DepartmentReqMessage) (*DepartmentMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedDepartmentServiceServer) Read(context.Context, *DepartmentReqMessage) (*DepartmentMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedDepartmentServiceServer) List(context.Context, *DepartmentReqMessage) (*ListDepartmentMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDepartmentServiceServer) DeleteDepartment(context.Context, *DepartmentReqMessage) (*DeleteDepartmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDepartment not implemented")
}
func (UnimplementedDepartmentServiceServer) DepartmentMemberList(context.Context, *DepartmentReqMessage) (*DepartmentMemberListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepartmentMemberList not implemented")
}
func (UnimplementedDepartmentServiceServer) SearchDepartmentMember(context.Context, *DepartmentReqMessage) (*DepartmentMemberListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchDepartmentMember not implemented")
}
func (UnimplementedDepartmentServiceServer) InviteDepartmentMember(context.Context, *DepartmentReqMessage) (*InviteDepartmentMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteDepartmentMember not implemented")
}
func (UnimplementedDepartmentServiceServer) RemoveDepartmentMember(context.Context, *DepartmentReqMessage) (*RemoveDepartmentMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDepartmentMember not implemented")
}
func (UnimplementedDepartmentServiceServer) DepartmentMemberDetail(context.Context, *DepartmentReqMessage) (*DepartmentMemberDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepartmentMemberDetail not implemented")
}
func (UnimplementedDepartmentServiceServer) mustEmbedUnimplementedDepartmentServiceServer() {}
func (UnimplementedDepartmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeDepartmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepartmentServiceServer will
// result in compilation errors.
type UnsafeDepartmentServiceServer interface {
	mustEmbedUnimplementedDepartmentServiceServer()
}

func RegisterDepartmentServiceServer(s grpc.ServiceRegistrar, srv DepartmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedDepartmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DepartmentService_ServiceDesc, srv)
}

func _DepartmentService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepartmentService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).Save(ctx, req.(*DepartmentReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepartmentService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).Read(ctx, req.(*DepartmentReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepartmentService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).List(ctx, req.(*DepartmentReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentService_DeleteDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).DeleteDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepartmentService_DeleteDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).DeleteDepartment(ctx, req.(*DepartmentReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentService_DepartmentMemberList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).DepartmentMemberList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepartmentService_DepartmentMemberList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).DepartmentMemberList(ctx, req.(*DepartmentReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentService_SearchDepartmentMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).SearchDepartmentMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepartmentService_SearchDepartmentMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).SearchDepartmentMember(ctx, req.(*DepartmentReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentService_InviteDepartmentMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).InviteDepartmentMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepartmentService_InviteDepartmentMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).InviteDepartmentMember(ctx, req.(*DepartmentReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentService_RemoveDepartmentMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).RemoveDepartmentMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepartmentService_RemoveDepartmentMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).RemoveDepartmentMember(ctx, req.(*DepartmentReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartmentService_DepartmentMemberDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartmentReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartmentServiceServer).DepartmentMemberDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepartmentService_DepartmentMemberDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartmentServiceServer).DepartmentMemberDetail(ctx, req.(*DepartmentReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// DepartmentService_ServiceDesc is the grpc.ServiceDesc for DepartmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepartmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "department.service.v1.DepartmentService",
	HandlerType: (*DepartmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _DepartmentService_Save_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _DepartmentService_Read_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DepartmentService_List_Handler,
		},
		{
			MethodName: "DeleteDepartment",
			Handler:    _DepartmentService_DeleteDepartment_Handler,
		},
		{
			MethodName: "DepartmentMemberList",
			Handler:    _DepartmentService_DepartmentMemberList_Handler,
		},
		{
			MethodName: "SearchDepartmentMember",
			Handler:    _DepartmentService_SearchDepartmentMember_Handler,
		},
		{
			MethodName: "InviteDepartmentMember",
			Handler:    _DepartmentService_InviteDepartmentMember_Handler,
		},
		{
			MethodName: "RemoveDepartmentMember",
			Handler:    _DepartmentService_RemoveDepartmentMember_Handler,
		},
		{
			MethodName: "DepartmentMemberDetail",
			Handler:    _DepartmentService_DepartmentMemberDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "department_service.proto",
}
