// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.0
// source: department_service.proto

package department

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepartmentReqMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MemberId             int64                  `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	OrganizationCode     string                 `protobuf:"bytes,2,opt,name=organizationCode,proto3" json:"organizationCode,omitempty"`
	Page                 int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	DepartmentCode       string                 `protobuf:"bytes,5,opt,name=departmentCode,proto3" json:"departmentCode,omitempty"`
	ParentDepartmentCode string                 `protobuf:"bytes,6,opt,name=parentDepartmentCode,proto3" json:"parentDepartmentCode,omitempty"`
	Name                 string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Keyword              string                 `protobuf:"bytes,8,opt,name=keyword,proto3" json:"keyword,omitempty"`
	AccountCode          string                 `protobuf:"bytes,9,opt,name=accountCode,proto3" json:"accountCode,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DepartmentReqMessage) Reset() {
	*x = DepartmentReqMessage{}
	mi := &file_department_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentReqMessage) ProtoMessage() {}

func (x *DepartmentReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentReqMessage.ProtoReflect.Descriptor instead.
func (*DepartmentReqMessage) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{0}
}

func (x *DepartmentReqMessage) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *DepartmentReqMessage) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *DepartmentReqMessage) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DepartmentReqMessage) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DepartmentReqMessage) GetDepartmentCode() string {
	if x != nil {
		return x.DepartmentCode
	}
	return ""
}

func (x *DepartmentReqMessage) GetParentDepartmentCode() string {
	if x != nil {
		return x.ParentDepartmentCode
	}
	return ""
}

func (x *DepartmentReqMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepartmentReqMessage) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *DepartmentReqMessage) GetAccountCode() string {
	if x != nil {
		return x.AccountCode
	}
	return ""
}

type DepartmentMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code             string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,3,opt,name=OrganizationCode,proto3" json:"OrganizationCode,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	CreateTime       string                 `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Pcode            string                 `protobuf:"bytes,6,opt,name=pcode,proto3" json:"pcode,omitempty"`
	Path             string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DepartmentMessage) Reset() {
	*x = DepartmentMessage{}
	mi := &file_department_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentMessage) ProtoMessage() {}

func (x *DepartmentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentMessage.ProtoReflect.Descriptor instead.
func (*DepartmentMessage) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{1}
}

func (x *DepartmentMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepartmentMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DepartmentMessage) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *DepartmentMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepartmentMessage) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *DepartmentMessage) GetPcode() string {
	if x != nil {
		return x.Pcode
	}
	return ""
}

func (x *DepartmentMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDepartmentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*DepartmentMessage   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentMessage) Reset() {
	*x = ListDepartmentMessage{}
	mi := &file_department_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentMessage) ProtoMessage() {}

func (x *ListDepartmentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentMessage.ProtoReflect.Descriptor instead.
func (*ListDepartmentMessage) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListDepartmentMessage) GetList() []*DepartmentMessage {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListDepartmentMessage) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentResponse) Reset() {
	*x = DeleteDepartmentResponse{}
	mi := &file_department_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentResponse) ProtoMessage() {}

func (x *DeleteDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{3}
}

type DepartmentMemberMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	IsPrincipal   int32                  `protobuf:"varint,6,opt,name=isPrincipal,proto3" json:"isPrincipal,omitempty"`
	AccountCode   string                 `protobuf:"bytes,7,opt,name=accountCode,proto3" json:"accountCode,omitempty"`
	Joined        bool                   `protobuf:"varint,8,opt,name=joined,proto3" json:"joined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentMemberMessage) Reset() {
	*x = DepartmentMemberMessage{}
	mi := &file_department_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentMemberMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentMemberMessage) ProtoMessage() {}

func (x *DepartmentMemberMessage) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentMemberMessage.ProtoReflect.Descriptor instead.
func (*DepartmentMemberMessage) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{4}
}

func (x *DepartmentMemberMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepartmentMemberMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepartmentMemberMessage) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *DepartmentMemberMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DepartmentMemberMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DepartmentMemberMessage) GetIsPrincipal() int32 {
	if x != nil {
		return x.IsPrincipal
	}
	return 0
}

func (x *DepartmentMemberMessage) GetAccountCode() string {
	if x != nil {
		return x.AccountCode
	}
	return ""
}

func (x *DepartmentMemberMessage) GetJoined() bool {
	if x != nil {
		return x.Joined
	}
	return false
}

type DepartmentMemberListResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	List          []*DepartmentMemberMessage `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentMemberListResponse) Reset() {
	*x = DepartmentMemberListResponse{}
	mi := &file_department_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentMemberListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentMemberListResponse) ProtoMessage() {}

func (x *DepartmentMemberListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentMemberListResponse.ProtoReflect.Descriptor instead.
func (*DepartmentMemberListResponse) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{5}
}

func (x *DepartmentMemberListResponse) GetList() []*DepartmentMemberMessage {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *DepartmentMemberListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DepartmentMemberDetailResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Member        *DepartmentMemberMessage `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentMemberDetailResponse) Reset() {
	*x = DepartmentMemberDetailResponse{}
	mi := &file_department_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentMemberDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentMemberDetailResponse) ProtoMessage() {}

func (x *DepartmentMemberDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentMemberDetailResponse.ProtoReflect.Descriptor instead.
func (*DepartmentMemberDetailResponse) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{6}
}

func (x *DepartmentMemberDetailResponse) GetMember() *DepartmentMemberMessage {
	if x != nil {
		return x.Member
	}
	return nil
}

type InviteDepartmentMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteDepartmentMemberResponse) Reset() {
	*x = InviteDepartmentMemberResponse{}
	mi := &file_department_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteDepartmentMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteDepartmentMemberResponse) ProtoMessage() {}

func (x *InviteDepartmentMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteDepartmentMemberResponse.ProtoReflect.Descriptor instead.
func (*InviteDepartmentMemberResponse) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{7}
}

type RemoveDepartmentMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDepartmentMemberResponse) Reset() {
	*x = RemoveDepartmentMemberResponse{}
	mi := &file_department_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDepartmentMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDepartmentMemberResponse) ProtoMessage() {}

func (x *RemoveDepartmentMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDepartmentMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveDepartmentMemberResponse) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{8}
}

var File_department_service_proto protoreflect.FileDescriptor

const file_department_service_proto_rawDesc = "" +
	"\n" +
	"\x18department_service.proto\x12\x15department.service.v1\"\xba\x02\n" +
	"\x14DepartmentReqMessage\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\x03R\bmemberId\x12*\n" +
	"\x10organizationCode\x18\x02 \x01(\tR\x10organizationCode\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\x12&\n" +
	"\x0edepartmentCode\x18\x05 \x01(\tR\x0edepartmentCode\x122\n" +
	"\x14parentDepartmentCode\x18\x06 \x01(\tR\x14parentDepartmentCode\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x18\n" +
	"\akeyword\x18\b \x01(\tR\akeyword\x12 \n" +
	"\vaccountCode\x18\t \x01(\tR\vaccountCode\"\xc1\x01\n" +
	"\x11DepartmentMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12*\n" +
	"\x10OrganizationCode\x18\x03 \x01(\tR\x10OrganizationCode\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"createTime\x18\x05 \x01(\tR\n" +
	"createTime\x12\x14\n" +
	"\x05pcode\x18\x06 \x01(\tR\x05pcode\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\"k\n" +
	"\x15ListDepartmentMessage\x12<\n" +
	"\x04list\x18\x01 \x03(\v2(.department.service.v1.DepartmentMessageR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x1a\n" +
	"\x18DeleteDepartmentResponse\"\xdb\x01\n" +
	"\x17DepartmentMemberMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12 \n" +
	"\visPrincipal\x18\x06 \x01(\x05R\visPrincipal\x12 \n" +
	"\vaccountCode\x18\a \x01(\tR\vaccountCode\x12\x16\n" +
	"\x06joined\x18\b \x01(\bR\x06joined\"x\n" +
	"\x1cDepartmentMemberListResponse\x12B\n" +
	"\x04list\x18\x01 \x03(\v2..department.service.v1.DepartmentMemberMessageR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"h\n" +
	"\x1eDepartmentMemberDetailResponse\x12F\n" +
	"\x06member\x18\x01 \x01(\v2..department.service.v1.DepartmentMemberMessageR\x06member\" \n" +
	"\x1eInviteDepartmentMemberResponse\" \n" +
	"\x1eRemoveDepartmentMemberResponse2\xa8\b\n" +
	"\x11DepartmentService\x12_\n" +
	"\x04Save\x12+.department.service.v1.DepartmentReqMessage\x1a(.department.service.v1.DepartmentMessage\"\x00\x12_\n" +
	"\x04Read\x12+.department.service.v1.DepartmentReqMessage\x1a(.department.service.v1.DepartmentMessage\"\x00\x12c\n" +
	"\x04List\x12+.department.service.v1.DepartmentReqMessage\x1a,.department.service.v1.ListDepartmentMessage\"\x00\x12r\n" +
	"\x10DeleteDepartment\x12+.department.service.v1.DepartmentReqMessage\x1a/.department.service.v1.DeleteDepartmentResponse\"\x00\x12z\n" +
	"\x14DepartmentMemberList\x12+.department.service.v1.DepartmentReqMessage\x1a3.department.service.v1.DepartmentMemberListResponse\"\x00\x12|\n" +
	"\x16SearchDepartmentMember\x12+.department.service.v1.DepartmentReqMessage\x1a3.department.service.v1.DepartmentMemberListResponse\"\x00\x12~\n" +
	"\x16InviteDepartmentMember\x12+.department.service.v1.DepartmentReqMessage\x1a5.department.service.v1.InviteDepartmentMemberResponse\"\x00\x12~\n" +
	"\x16RemoveDepartmentMember\x12+.department.service.v1.DepartmentReqMessage\x1a5.department.service.v1.RemoveDepartmentMemberResponse\"\x00\x12~\n" +
	"\x16DepartmentMemberDetail\x12+.department.service.v1.DepartmentReqMessage\x1a5.department.service.v1.DepartmentMemberDetailResponse\"\x00B\"Z test.com/project-grpc/departmentb\x06proto3"

var (
	file_department_service_proto_rawDescOnce sync.Once
	file_department_service_proto_rawDescData []byte
)

func file_department_service_proto_rawDescGZIP() []byte {
	file_department_service_proto_rawDescOnce.Do(func() {
		file_department_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_department_service_proto_rawDesc), len(file_department_service_proto_rawDesc)))
	})
	return file_department_service_proto_rawDescData
}

var file_department_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_department_service_proto_goTypes = []any{
	(*DepartmentReqMessage)(nil),           // 0: department.service.v1.DepartmentReqMessage
	(*DepartmentMessage)(nil),              // 1: department.service.v1.DepartmentMessage
	(*ListDepartmentMessage)(nil),          // 2: department.service.v1.ListDepartmentMessage
	(*DeleteDepartmentResponse)(nil),       // 3: department.service.v1.DeleteDepartmentResponse
	(*DepartmentMemberMessage)(nil),        // 4: department.service.v1.DepartmentMemberMessage
	(*DepartmentMemberListResponse)(nil),   // 5: department.service.v1.DepartmentMemberListResponse
	(*DepartmentMemberDetailResponse)(nil), // 6: department.service.v1.DepartmentMemberDetailResponse
	(*InviteDepartmentMemberResponse)(nil), // 7: department.service.v1.InviteDepartmentMemberResponse
	(*RemoveDepartmentMemberResponse)(nil), // 8: department.service.v1.RemoveDepartmentMemberResponse
}
var file_department_service_proto_depIdxs = []int32{
	1,  // 0: department.service.v1.ListDepartmentMessage.list:type_name -> department.service.v1.DepartmentMessage
	4,  // 1: department.service.v1.DepartmentMemberListResponse.list:type_name -> department.service.v1.DepartmentMemberMessage
	4,  // 2: department.service.v1.DepartmentMemberDetailResponse.member:type_name -> department.service.v1.DepartmentMemberMessage
	0,  // 3: department.service.v1.DepartmentService.Save:input_type -> department.service.v1.DepartmentReqMessage
	0,  // 4: department.service.v1.DepartmentService.Read:input_type -> department.service.v1.DepartmentReqMessage
	0,  // 5: department.service.v1.DepartmentService.List:input_type -> department.service.v1.DepartmentReqMessage
	0,  // 6: department.service.v1.DepartmentService.DeleteDepartment:input_type -> department.service.v1.DepartmentReqMessage
	0,  // 7: department.service.v1.DepartmentService.DepartmentMemberList:input_type -> department.service.v1.DepartmentReqMessage
	0,  // 8: department.service.v1.DepartmentService.SearchDepartmentMember:input_type -> department.service.v1.DepartmentReqMessage
	0,  // 9: department.service.v1.DepartmentService.InviteDepartmentMember:input_type -> department.service.v1.DepartmentReqMessage
	0,  // 10: department.service.v1.DepartmentService.RemoveDepartmentMember:input_type -> department.service.v1.DepartmentReqMessage
	0,  // 11: department.service.v1.DepartmentService.DepartmentMemberDetail:input_type -> department.service.v1.DepartmentReqMessage
	1,  // 12: department.service.v1.DepartmentService.Save:output_type -> department.service.v1.DepartmentMessage
	1,  // 13: department.service.v1.DepartmentService.Read:output_type -> department.service.v1.DepartmentMessage
	2,  // 14: department.service.v1.DepartmentService.List:output_type -> department.service.v1.ListDepartmentMessage
	3,  // 15: department.service.v1.DepartmentService.DeleteDepartment:output_type -> department.service.v1.DeleteDepartmentResponse
	5,  // 16: department.service.v1.DepartmentService.DepartmentMemberList:output_type -> department.service.v1.DepartmentMemberListResponse
	5,  // 17: department.service.v1.DepartmentService.SearchDepartmentMember:output_type -> department.service.v1.DepartmentMemberListResponse
	7,  // 18: department.service.v1.DepartmentService.InviteDepartmentMember:output_type -> department.service.v1.InviteDepartmentMemberResponse
	8,  // 19: department.service.v1.DepartmentService.RemoveDepartmentMember:output_type -> department.service.v1.RemoveDepartmentMemberResponse
	6,  // 20: department.service.v1.DepartmentService.DepartmentMemberDetail:output_type -> department.service.v1.DepartmentMemberDetailResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_department_service_proto_init() }
func file_department_service_proto_init() {
	if File_department_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_department_service_proto_rawDesc), len(file_department_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_department_service_proto_goTypes,
		DependencyIndexes: file_department_service_proto_depIdxs,
		MessageInfos:      file_department_service_proto_msgTypes,
	}.Build()
	File_department_service_proto = out.File
	file_department_service_proto_goTypes = nil
	file_department_service_proto_depIdxs = nil
}
