// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: project_service.proto

package project

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectService_Index_FullMethodName                 = "/project.service.v1.ProjectService/Index"
	ProjectService_FindProjectByMemId_FullMethodName    = "/project.service.v1.ProjectService/FindProjectByMemId"
	ProjectService_FindProjectTemplate_FullMethodName   = "/project.service.v1.ProjectService/FindProjectTemplate"
	ProjectService_SaveProjectTemplate_FullMethodName   = "/project.service.v1.ProjectService/SaveProjectTemplate"
	ProjectService_UpdateProjectTemplate_FullMethodName = "/project.service.v1.ProjectService/UpdateProjectTemplate"
	ProjectService_DeleteProjectTemplate_FullMethodName = "/project.service.v1.ProjectService/DeleteProjectTemplate"
	ProjectService_SaveProject_FullMethodName           = "/project.service.v1.ProjectService/SaveProject"
	ProjectService_FindProjectDetail_FullMethodName     = "/project.service.v1.ProjectService/FindProjectDetail"
	ProjectService_UpdateDeletedProject_FullMethodName  = "/project.service.v1.ProjectService/UpdateDeletedProject"
	ProjectService_UpdateCollectProject_FullMethodName  = "/project.service.v1.ProjectService/UpdateCollectProject"
	ProjectService_UpdateProject_FullMethodName         = "/project.service.v1.ProjectService/UpdateProject"
	ProjectService_GetLogBySelfProject_FullMethodName   = "/project.service.v1.ProjectService/GetLogBySelfProject"
	ProjectService_NodeList_FullMethodName              = "/project.service.v1.ProjectService/NodeList"
	ProjectService_FindProjectByMemberId_FullMethodName = "/project.service.v1.ProjectService/FindProjectByMemberId"
	ProjectService_QuitProject_FullMethodName           = "/project.service.v1.ProjectService/QuitProject"
	ProjectService_ArchiveProject_FullMethodName        = "/project.service.v1.ProjectService/ArchiveProject"
	ProjectService_RecoveryArchive_FullMethodName       = "/project.service.v1.ProjectService/RecoveryArchive"
	ProjectService_DeleteProject_FullMethodName         = "/project.service.v1.ProjectService/DeleteProject"
	ProjectService_ProjectAnalysis_FullMethodName       = "/project.service.v1.ProjectService/ProjectAnalysis"
	ProjectService_SearchInviteMember_FullMethodName    = "/project.service.v1.ProjectService/SearchInviteMember"
	ProjectService_InviteMember_FullMethodName          = "/project.service.v1.ProjectService/InviteMember"
	ProjectService_JoinByInviteLink_FullMethodName      = "/project.service.v1.ProjectService/JoinByInviteLink"
	ProjectService_RemoveMember_FullMethodName          = "/project.service.v1.ProjectService/RemoveMember"
	ProjectService_ListForInvite_FullMethodName         = "/project.service.v1.ProjectService/ListForInvite"
)

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServiceClient interface {
	Index(ctx context.Context, in *IndexMessage, opts ...grpc.CallOption) (*IndexResponse, error)
	FindProjectByMemId(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*MyProjectResponse, error)
	FindProjectTemplate(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectTemplateResponse, error)
	SaveProjectTemplate(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectTemplateMessage, error)
	UpdateProjectTemplate(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectBoolResponse, error)
	DeleteProjectTemplate(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectBoolResponse, error)
	SaveProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*SaveProjectMessage, error)
	FindProjectDetail(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectDetailMessage, error)
	UpdateDeletedProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*DeletedProjectResponse, error)
	UpdateCollectProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*CollectProjectResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectMessage, opts ...grpc.CallOption) (*UpdateProjectResponse, error)
	GetLogBySelfProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectLogResponse, error)
	NodeList(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectNodeResponseMessage, error)
	FindProjectByMemberId(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*FindProjectByMemberIdResponse, error)
	QuitProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*QuitProjectResponse, error)
	ArchiveProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ArchiveProjectResponse, error)
	RecoveryArchive(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*RecoveryArchiveResponse, error)
	DeleteProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*DeleteProjectResponse, error)
	ProjectAnalysis(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectAnalysisResponse, error)
	SearchInviteMember(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*SearchInviteMemberResponse, error)
	InviteMember(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*InviteMemberResponse, error)
	JoinByInviteLink(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*JoinByInviteLinkResponse, error)
	RemoveMember(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*RemoveMemberResponse, error)
	ListForInvite(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ListForInviteResponse, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) Index(ctx context.Context, in *IndexMessage, opts ...grpc.CallOption) (*IndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, ProjectService_Index_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) FindProjectByMemId(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*MyProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MyProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_FindProjectByMemId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) FindProjectTemplate(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectTemplateResponse)
	err := c.cc.Invoke(ctx, ProjectService_FindProjectTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SaveProjectTemplate(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectTemplateMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectTemplateMessage)
	err := c.cc.Invoke(ctx, ProjectService_SaveProjectTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProjectTemplate(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectBoolResponse)
	err := c.cc.Invoke(ctx, ProjectService_UpdateProjectTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteProjectTemplate(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectBoolResponse)
	err := c.cc.Invoke(ctx, ProjectService_DeleteProjectTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SaveProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*SaveProjectMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveProjectMessage)
	err := c.cc.Invoke(ctx, ProjectService_SaveProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) FindProjectDetail(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectDetailMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectDetailMessage)
	err := c.cc.Invoke(ctx, ProjectService_FindProjectDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateDeletedProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*DeletedProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletedProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_UpdateDeletedProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateCollectProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*CollectProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_UpdateCollectProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectMessage, opts ...grpc.CallOption) (*UpdateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_UpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetLogBySelfProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectLogResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetLogBySelfProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) NodeList(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectNodeResponseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectNodeResponseMessage)
	err := c.cc.Invoke(ctx, ProjectService_NodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) FindProjectByMemberId(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*FindProjectByMemberIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindProjectByMemberIdResponse)
	err := c.cc.Invoke(ctx, ProjectService_FindProjectByMemberId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) QuitProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*QuitProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuitProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_QuitProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ArchiveProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ArchiveProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_ArchiveProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) RecoveryArchive(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*RecoveryArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoveryArchiveResponse)
	err := c.cc.Invoke(ctx, ProjectService_RecoveryArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteProject(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*DeleteProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ProjectAnalysis(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ProjectAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectAnalysisResponse)
	err := c.cc.Invoke(ctx, ProjectService_ProjectAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SearchInviteMember(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*SearchInviteMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchInviteMemberResponse)
	err := c.cc.Invoke(ctx, ProjectService_SearchInviteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) InviteMember(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*InviteMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteMemberResponse)
	err := c.cc.Invoke(ctx, ProjectService_InviteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) JoinByInviteLink(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*JoinByInviteLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinByInviteLinkResponse)
	err := c.cc.Invoke(ctx, ProjectService_JoinByInviteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) RemoveMember(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*RemoveMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemberResponse)
	err := c.cc.Invoke(ctx, ProjectService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListForInvite(ctx context.Context, in *ProjectRpcMessage, opts ...grpc.CallOption) (*ListForInviteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListForInviteResponse)
	err := c.cc.Invoke(ctx, ProjectService_ListForInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility.
type ProjectServiceServer interface {
	Index(context.Context, *IndexMessage) (*IndexResponse, error)
	FindProjectByMemId(context.Context, *ProjectRpcMessage) (*MyProjectResponse, error)
	FindProjectTemplate(context.Context, *ProjectRpcMessage) (*ProjectTemplateResponse, error)
	SaveProjectTemplate(context.Context, *ProjectRpcMessage) (*ProjectTemplateMessage, error)
	UpdateProjectTemplate(context.Context, *ProjectRpcMessage) (*ProjectBoolResponse, error)
	DeleteProjectTemplate(context.Context, *ProjectRpcMessage) (*ProjectBoolResponse, error)
	SaveProject(context.Context, *ProjectRpcMessage) (*SaveProjectMessage, error)
	FindProjectDetail(context.Context, *ProjectRpcMessage) (*ProjectDetailMessage, error)
	UpdateDeletedProject(context.Context, *ProjectRpcMessage) (*DeletedProjectResponse, error)
	UpdateCollectProject(context.Context, *ProjectRpcMessage) (*CollectProjectResponse, error)
	UpdateProject(context.Context, *UpdateProjectMessage) (*UpdateProjectResponse, error)
	GetLogBySelfProject(context.Context, *ProjectRpcMessage) (*ProjectLogResponse, error)
	NodeList(context.Context, *ProjectRpcMessage) (*ProjectNodeResponseMessage, error)
	FindProjectByMemberId(context.Context, *ProjectRpcMessage) (*FindProjectByMemberIdResponse, error)
	QuitProject(context.Context, *ProjectRpcMessage) (*QuitProjectResponse, error)
	ArchiveProject(context.Context, *ProjectRpcMessage) (*ArchiveProjectResponse, error)
	RecoveryArchive(context.Context, *ProjectRpcMessage) (*RecoveryArchiveResponse, error)
	DeleteProject(context.Context, *ProjectRpcMessage) (*DeleteProjectResponse, error)
	ProjectAnalysis(context.Context, *ProjectRpcMessage) (*ProjectAnalysisResponse, error)
	SearchInviteMember(context.Context, *ProjectRpcMessage) (*SearchInviteMemberResponse, error)
	InviteMember(context.Context, *ProjectRpcMessage) (*InviteMemberResponse, error)
	JoinByInviteLink(context.Context, *ProjectRpcMessage) (*JoinByInviteLinkResponse, error)
	RemoveMember(context.Context, *ProjectRpcMessage) (*RemoveMemberResponse, error)
	ListForInvite(context.Context, *ProjectRpcMessage) (*ListForInviteResponse, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectServiceServer struct{}

func (UnimplementedProjectServiceServer) Index(context.Context, *IndexMessage) (*IndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Index not implemented")
}
func (UnimplementedProjectServiceServer) FindProjectByMemId(context.Context, *ProjectRpcMessage) (*MyProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindProjectByMemId not implemented")
}
func (UnimplementedProjectServiceServer) FindProjectTemplate(context.Context, *ProjectRpcMessage) (*ProjectTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindProjectTemplate not implemented")
}
func (UnimplementedProjectServiceServer) SaveProjectTemplate(context.Context, *ProjectRpcMessage) (*ProjectTemplateMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveProjectTemplate not implemented")
}
func (UnimplementedProjectServiceServer) UpdateProjectTemplate(context.Context, *ProjectRpcMessage) (*ProjectBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectTemplate not implemented")
}
func (UnimplementedProjectServiceServer) DeleteProjectTemplate(context.Context, *ProjectRpcMessage) (*ProjectBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProjectTemplate not implemented")
}
func (UnimplementedProjectServiceServer) SaveProject(context.Context, *ProjectRpcMessage) (*SaveProjectMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveProject not implemented")
}
func (UnimplementedProjectServiceServer) FindProjectDetail(context.Context, *ProjectRpcMessage) (*ProjectDetailMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindProjectDetail not implemented")
}
func (UnimplementedProjectServiceServer) UpdateDeletedProject(context.Context, *ProjectRpcMessage) (*DeletedProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeletedProject not implemented")
}
func (UnimplementedProjectServiceServer) UpdateCollectProject(context.Context, *ProjectRpcMessage) (*CollectProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCollectProject not implemented")
}
func (UnimplementedProjectServiceServer) UpdateProject(context.Context, *UpdateProjectMessage) (*UpdateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedProjectServiceServer) GetLogBySelfProject(context.Context, *ProjectRpcMessage) (*ProjectLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogBySelfProject not implemented")
}
func (UnimplementedProjectServiceServer) NodeList(context.Context, *ProjectRpcMessage) (*ProjectNodeResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeList not implemented")
}
func (UnimplementedProjectServiceServer) FindProjectByMemberId(context.Context, *ProjectRpcMessage) (*FindProjectByMemberIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindProjectByMemberId not implemented")
}
func (UnimplementedProjectServiceServer) QuitProject(context.Context, *ProjectRpcMessage) (*QuitProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitProject not implemented")
}
func (UnimplementedProjectServiceServer) ArchiveProject(context.Context, *ProjectRpcMessage) (*ArchiveProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveProject not implemented")
}
func (UnimplementedProjectServiceServer) RecoveryArchive(context.Context, *ProjectRpcMessage) (*RecoveryArchiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoveryArchive not implemented")
}
func (UnimplementedProjectServiceServer) DeleteProject(context.Context, *ProjectRpcMessage) (*DeleteProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedProjectServiceServer) ProjectAnalysis(context.Context, *ProjectRpcMessage) (*ProjectAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProjectAnalysis not implemented")
}
func (UnimplementedProjectServiceServer) SearchInviteMember(context.Context, *ProjectRpcMessage) (*SearchInviteMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchInviteMember not implemented")
}
func (UnimplementedProjectServiceServer) InviteMember(context.Context, *ProjectRpcMessage) (*InviteMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteMember not implemented")
}
func (UnimplementedProjectServiceServer) JoinByInviteLink(context.Context, *ProjectRpcMessage) (*JoinByInviteLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinByInviteLink not implemented")
}
func (UnimplementedProjectServiceServer) RemoveMember(context.Context, *ProjectRpcMessage) (*RemoveMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedProjectServiceServer) ListForInvite(context.Context, *ProjectRpcMessage) (*ListForInviteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListForInvite not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}
func (UnimplementedProjectServiceServer) testEmbeddedByValue()                        {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	// If the following call pancis, it indicates UnimplementedProjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Index_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Index(ctx, req.(*IndexMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_FindProjectByMemId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).FindProjectByMemId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_FindProjectByMemId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).FindProjectByMemId(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_FindProjectTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).FindProjectTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_FindProjectTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).FindProjectTemplate(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SaveProjectTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SaveProjectTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_SaveProjectTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SaveProjectTemplate(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProjectTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProjectTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateProjectTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProjectTemplate(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteProjectTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteProjectTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_DeleteProjectTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteProjectTemplate(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SaveProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SaveProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_SaveProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SaveProject(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_FindProjectDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).FindProjectDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_FindProjectDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).FindProjectDetail(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateDeletedProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateDeletedProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateDeletedProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateDeletedProject(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateCollectProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateCollectProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateCollectProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateCollectProject(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProject(ctx, req.(*UpdateProjectMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetLogBySelfProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetLogBySelfProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetLogBySelfProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetLogBySelfProject(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_NodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).NodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_NodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).NodeList(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_FindProjectByMemberId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).FindProjectByMemberId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_FindProjectByMemberId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).FindProjectByMemberId(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_QuitProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).QuitProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_QuitProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).QuitProject(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ArchiveProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ArchiveProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ArchiveProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ArchiveProject(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_RecoveryArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).RecoveryArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_RecoveryArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).RecoveryArchive(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteProject(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ProjectAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ProjectAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ProjectAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ProjectAnalysis(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SearchInviteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SearchInviteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_SearchInviteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SearchInviteMember(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_InviteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).InviteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_InviteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).InviteMember(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_JoinByInviteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).JoinByInviteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_JoinByInviteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).JoinByInviteLink(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).RemoveMember(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListForInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRpcMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListForInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ListForInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListForInvite(ctx, req.(*ProjectRpcMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project.service.v1.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _ProjectService_Index_Handler,
		},
		{
			MethodName: "FindProjectByMemId",
			Handler:    _ProjectService_FindProjectByMemId_Handler,
		},
		{
			MethodName: "FindProjectTemplate",
			Handler:    _ProjectService_FindProjectTemplate_Handler,
		},
		{
			MethodName: "SaveProjectTemplate",
			Handler:    _ProjectService_SaveProjectTemplate_Handler,
		},
		{
			MethodName: "UpdateProjectTemplate",
			Handler:    _ProjectService_UpdateProjectTemplate_Handler,
		},
		{
			MethodName: "DeleteProjectTemplate",
			Handler:    _ProjectService_DeleteProjectTemplate_Handler,
		},
		{
			MethodName: "SaveProject",
			Handler:    _ProjectService_SaveProject_Handler,
		},
		{
			MethodName: "FindProjectDetail",
			Handler:    _ProjectService_FindProjectDetail_Handler,
		},
		{
			MethodName: "UpdateDeletedProject",
			Handler:    _ProjectService_UpdateDeletedProject_Handler,
		},
		{
			MethodName: "UpdateCollectProject",
			Handler:    _ProjectService_UpdateCollectProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _ProjectService_UpdateProject_Handler,
		},
		{
			MethodName: "GetLogBySelfProject",
			Handler:    _ProjectService_GetLogBySelfProject_Handler,
		},
		{
			MethodName: "NodeList",
			Handler:    _ProjectService_NodeList_Handler,
		},
		{
			MethodName: "FindProjectByMemberId",
			Handler:    _ProjectService_FindProjectByMemberId_Handler,
		},
		{
			MethodName: "QuitProject",
			Handler:    _ProjectService_QuitProject_Handler,
		},
		{
			MethodName: "ArchiveProject",
			Handler:    _ProjectService_ArchiveProject_Handler,
		},
		{
			MethodName: "RecoveryArchive",
			Handler:    _ProjectService_RecoveryArchive_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _ProjectService_DeleteProject_Handler,
		},
		{
			MethodName: "ProjectAnalysis",
			Handler:    _ProjectService_ProjectAnalysis_Handler,
		},
		{
			MethodName: "SearchInviteMember",
			Handler:    _ProjectService_SearchInviteMember_Handler,
		},
		{
			MethodName: "InviteMember",
			Handler:    _ProjectService_InviteMember_Handler,
		},
		{
			MethodName: "JoinByInviteLink",
			Handler:    _ProjectService_JoinByInviteLink_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _ProjectService_RemoveMember_Handler,
		},
		{
			MethodName: "ListForInvite",
			Handler:    _ProjectService_ListForInvite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "project_service.proto",
}
