// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.0
// source: auth_service.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthReqMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MemberId         int64                  `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,2,opt,name=organizationCode,proto3" json:"organizationCode,omitempty"`
	Page             int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Action           string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	AuthId           int64                  `protobuf:"varint,6,opt,name=authId,proto3" json:"authId,omitempty"`
	Nodes            []string               `protobuf:"bytes,7,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Title            string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Desc             string                 `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`
	Status           int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Sort             int32                  `protobuf:"varint,11,opt,name=sort,proto3" json:"sort,omitempty"`
	Type             string                 `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthReqMessage) Reset() {
	*x = AuthReqMessage{}
	mi := &file_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReqMessage) ProtoMessage() {}

func (x *AuthReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReqMessage.ProtoReflect.Descriptor instead.
func (*AuthReqMessage) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuthReqMessage) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *AuthReqMessage) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *AuthReqMessage) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AuthReqMessage) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AuthReqMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuthReqMessage) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *AuthReqMessage) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *AuthReqMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AuthReqMessage) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AuthReqMessage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuthReqMessage) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *AuthReqMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ProjectAuth struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,2,opt,name=OrganizationCode,proto3" json:"OrganizationCode,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	CreateAt         string                 `protobuf:"bytes,4,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	Sort             int32                  `protobuf:"varint,5,opt,name=Sort,proto3" json:"Sort,omitempty"`
	Status           int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Desc             string                 `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	CreateBy         int64                  `protobuf:"varint,8,opt,name=CreateBy,proto3" json:"CreateBy,omitempty"`
	IsDefault        int32                  `protobuf:"varint,9,opt,name=IsDefault,proto3" json:"IsDefault,omitempty"`
	Type             string                 `protobuf:"bytes,10,opt,name=Type,proto3" json:"Type,omitempty"`
	CanDelete        int32                  `protobuf:"varint,11,opt,name=CanDelete,proto3" json:"CanDelete,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProjectAuth) Reset() {
	*x = ProjectAuth{}
	mi := &file_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectAuth) ProtoMessage() {}

func (x *ProjectAuth) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectAuth.ProtoReflect.Descriptor instead.
func (*ProjectAuth) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectAuth) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectAuth) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *ProjectAuth) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProjectAuth) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *ProjectAuth) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProjectAuth) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProjectAuth) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ProjectAuth) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *ProjectAuth) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *ProjectAuth) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProjectAuth) GetCanDelete() int32 {
	if x != nil {
		return x.CanDelete
	}
	return 0
}

type ListAuthMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ProjectAuth         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthMessage) Reset() {
	*x = ListAuthMessage{}
	mi := &file_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthMessage) ProtoMessage() {}

func (x *ListAuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthMessage.ProtoReflect.Descriptor instead.
func (*ListAuthMessage) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListAuthMessage) GetList() []*ProjectAuth {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListAuthMessage) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ProjectNodeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Pnode         string                 `protobuf:"bytes,4,opt,name=pnode,proto3" json:"pnode,omitempty"`
	IsLogin       int32                  `protobuf:"varint,5,opt,name=isLogin,proto3" json:"isLogin,omitempty"`
	IsMenu        int32                  `protobuf:"varint,6,opt,name=isMenu,proto3" json:"isMenu,omitempty"`
	IsAuth        int32                  `protobuf:"varint,7,opt,name=isAuth,proto3" json:"isAuth,omitempty"`
	Checked       bool                   `protobuf:"varint,8,opt,name=checked,proto3" json:"checked,omitempty"`
	Key           string                 `protobuf:"bytes,9,opt,name=key,proto3" json:"key,omitempty"`
	Children      []*ProjectNodeMessage  `protobuf:"bytes,10,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectNodeMessage) Reset() {
	*x = ProjectNodeMessage{}
	mi := &file_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectNodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectNodeMessage) ProtoMessage() {}

func (x *ProjectNodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectNodeMessage.ProtoReflect.Descriptor instead.
func (*ProjectNodeMessage) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectNodeMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectNodeMessage) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ProjectNodeMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProjectNodeMessage) GetPnode() string {
	if x != nil {
		return x.Pnode
	}
	return ""
}

func (x *ProjectNodeMessage) GetIsLogin() int32 {
	if x != nil {
		return x.IsLogin
	}
	return 0
}

func (x *ProjectNodeMessage) GetIsMenu() int32 {
	if x != nil {
		return x.IsMenu
	}
	return 0
}

func (x *ProjectNodeMessage) GetIsAuth() int32 {
	if x != nil {
		return x.IsAuth
	}
	return 0
}

func (x *ProjectNodeMessage) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

func (x *ProjectNodeMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProjectNodeMessage) GetChildren() []*ProjectNodeMessage {
	if x != nil {
		return x.Children
	}
	return nil
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ProjectNodeMessage  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	CheckedList   []string               `protobuf:"bytes,2,rep,name=checkedList,proto3" json:"checkedList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyResponse) GetList() []*ProjectNodeMessage {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ApplyResponse) GetCheckedList() []string {
	if x != nil {
		return x.CheckedList
	}
	return nil
}

type AuthNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []string               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthNodesResponse) Reset() {
	*x = AuthNodesResponse{}
	mi := &file_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthNodesResponse) ProtoMessage() {}

func (x *AuthNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthNodesResponse.ProtoReflect.Descriptor instead.
func (*AuthNodesResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *AuthNodesResponse) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type DeleteAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAuthResponse) Reset() {
	*x = DeleteAuthResponse{}
	mi := &file_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuthResponse) ProtoMessage() {}

func (x *DeleteAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuthResponse.ProtoReflect.Descriptor instead.
func (*DeleteAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_rawDescGZIP(), []int{6}
}

var File_auth_service_proto protoreflect.FileDescriptor

const file_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x12auth_service.proto\x12\x0fauth.service.v1\"\xb8\x02\n" +
	"\x0eAuthReqMessage\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\x03R\bmemberId\x12*\n" +
	"\x10organizationCode\x18\x02 \x01(\tR\x10organizationCode\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x16\n" +
	"\x06authId\x18\x06 \x01(\x03R\x06authId\x12\x14\n" +
	"\x05nodes\x18\a \x03(\tR\x05nodes\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\t \x01(\tR\x04desc\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x12\n" +
	"\x04sort\x18\v \x01(\x05R\x04sort\x12\x12\n" +
	"\x04type\x18\f \x01(\tR\x04type\"\xa7\x02\n" +
	"\vProjectAuth\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x10OrganizationCode\x18\x02 \x01(\tR\x10OrganizationCode\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x12\x1a\n" +
	"\bCreateAt\x18\x04 \x01(\tR\bCreateAt\x12\x12\n" +
	"\x04Sort\x18\x05 \x01(\x05R\x04Sort\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x12\n" +
	"\x04desc\x18\a \x01(\tR\x04desc\x12\x1a\n" +
	"\bCreateBy\x18\b \x01(\x03R\bCreateBy\x12\x1c\n" +
	"\tIsDefault\x18\t \x01(\x05R\tIsDefault\x12\x12\n" +
	"\x04Type\x18\n" +
	" \x01(\tR\x04Type\x12\x1c\n" +
	"\tCanDelete\x18\v \x01(\x05R\tCanDelete\"Y\n" +
	"\x0fListAuthMessage\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.auth.service.v1.ProjectAuthR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x9b\x02\n" +
	"\x12ProjectNodeMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05pnode\x18\x04 \x01(\tR\x05pnode\x12\x18\n" +
	"\aisLogin\x18\x05 \x01(\x05R\aisLogin\x12\x16\n" +
	"\x06isMenu\x18\x06 \x01(\x05R\x06isMenu\x12\x16\n" +
	"\x06isAuth\x18\a \x01(\x05R\x06isAuth\x12\x18\n" +
	"\achecked\x18\b \x01(\bR\achecked\x12\x10\n" +
	"\x03key\x18\t \x01(\tR\x03key\x12?\n" +
	"\bchildren\x18\n" +
	" \x03(\v2#.auth.service.v1.ProjectNodeMessageR\bchildren\"j\n" +
	"\rApplyResponse\x127\n" +
	"\x04list\x18\x01 \x03(\v2#.auth.service.v1.ProjectNodeMessageR\x04list\x12 \n" +
	"\vcheckedList\x18\x02 \x03(\tR\vcheckedList\"'\n" +
	"\x11AuthNodesResponse\x12\x12\n" +
	"\x04list\x18\x01 \x03(\tR\x04list\"\x14\n" +
	"\x12DeleteAuthResponse2\xd3\x04\n" +
	"\vAuthService\x12O\n" +
	"\bAuthList\x12\x1f.auth.service.v1.AuthReqMessage\x1a .auth.service.v1.ListAuthMessage\"\x00\x12J\n" +
	"\x05Apply\x12\x1f.auth.service.v1.AuthReqMessage\x1a\x1e.auth.service.v1.ApplyResponse\"\x00\x12\\\n" +
	"\x13AuthNodesByMemberId\x12\x1f.auth.service.v1.AuthReqMessage\x1a\".auth.service.v1.AuthNodesResponse\"\x00\x12M\n" +
	"\bSaveAuth\x12\x1f.auth.service.v1.AuthReqMessage\x1a\x1e.auth.service.v1.ApplyResponse\"\x00\x12O\n" +
	"\n" +
	"UpdateAuth\x12\x1f.auth.service.v1.AuthReqMessage\x1a\x1e.auth.service.v1.ApplyResponse\"\x00\x12S\n" +
	"\x0eSetDefaultAuth\x12\x1f.auth.service.v1.AuthReqMessage\x1a\x1e.auth.service.v1.ApplyResponse\"\x00\x12T\n" +
	"\n" +
	"DeleteAuth\x12\x1f.auth.service.v1.AuthReqMessage\x1a#.auth.service.v1.DeleteAuthResponse\"\x00B\x1cZ\x1atest.com/project-grpc/authb\x06proto3"

var (
	file_auth_service_proto_rawDescOnce sync.Once
	file_auth_service_proto_rawDescData []byte
)

func file_auth_service_proto_rawDescGZIP() []byte {
	file_auth_service_proto_rawDescOnce.Do(func() {
		file_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_service_proto_rawDesc), len(file_auth_service_proto_rawDesc)))
	})
	return file_auth_service_proto_rawDescData
}

var file_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_service_proto_goTypes = []any{
	(*AuthReqMessage)(nil),     // 0: auth.service.v1.AuthReqMessage
	(*ProjectAuth)(nil),        // 1: auth.service.v1.ProjectAuth
	(*ListAuthMessage)(nil),    // 2: auth.service.v1.ListAuthMessage
	(*ProjectNodeMessage)(nil), // 3: auth.service.v1.ProjectNodeMessage
	(*ApplyResponse)(nil),      // 4: auth.service.v1.ApplyResponse
	(*AuthNodesResponse)(nil),  // 5: auth.service.v1.AuthNodesResponse
	(*DeleteAuthResponse)(nil), // 6: auth.service.v1.DeleteAuthResponse
}
var file_auth_service_proto_depIdxs = []int32{
	1,  // 0: auth.service.v1.ListAuthMessage.list:type_name -> auth.service.v1.ProjectAuth
	3,  // 1: auth.service.v1.ProjectNodeMessage.children:type_name -> auth.service.v1.ProjectNodeMessage
	3,  // 2: auth.service.v1.ApplyResponse.list:type_name -> auth.service.v1.ProjectNodeMessage
	0,  // 3: auth.service.v1.AuthService.AuthList:input_type -> auth.service.v1.AuthReqMessage
	0,  // 4: auth.service.v1.AuthService.Apply:input_type -> auth.service.v1.AuthReqMessage
	0,  // 5: auth.service.v1.AuthService.AuthNodesByMemberId:input_type -> auth.service.v1.AuthReqMessage
	0,  // 6: auth.service.v1.AuthService.SaveAuth:input_type -> auth.service.v1.AuthReqMessage
	0,  // 7: auth.service.v1.AuthService.UpdateAuth:input_type -> auth.service.v1.AuthReqMessage
	0,  // 8: auth.service.v1.AuthService.SetDefaultAuth:input_type -> auth.service.v1.AuthReqMessage
	0,  // 9: auth.service.v1.AuthService.DeleteAuth:input_type -> auth.service.v1.AuthReqMessage
	2,  // 10: auth.service.v1.AuthService.AuthList:output_type -> auth.service.v1.ListAuthMessage
	4,  // 11: auth.service.v1.AuthService.Apply:output_type -> auth.service.v1.ApplyResponse
	5,  // 12: auth.service.v1.AuthService.AuthNodesByMemberId:output_type -> auth.service.v1.AuthNodesResponse
	4,  // 13: auth.service.v1.AuthService.SaveAuth:output_type -> auth.service.v1.ApplyResponse
	4,  // 14: auth.service.v1.AuthService.UpdateAuth:output_type -> auth.service.v1.ApplyResponse
	4,  // 15: auth.service.v1.AuthService.SetDefaultAuth:output_type -> auth.service.v1.ApplyResponse
	6,  // 16: auth.service.v1.AuthService.DeleteAuth:output_type -> auth.service.v1.DeleteAuthResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_auth_service_proto_init() }
func file_auth_service_proto_init() {
	if File_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_proto_rawDesc), len(file_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_proto_goTypes,
		DependencyIndexes: file_auth_service_proto_depIdxs,
		MessageInfos:      file_auth_service_proto_msgTypes,
	}.Build()
	File_auth_service_proto = out.File
	file_auth_service_proto_goTypes = nil
	file_auth_service_proto_depIdxs = nil
}
