// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.0
// source: account_service.proto

package account

import (
	"reflect"
	"sync"
	"unsafe"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountReqMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MemberId         int64                  `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	ProjectCode      string                 `protobuf:"bytes,2,opt,name=projectCode,proto3" json:"projectCode,omitempty"`
	Page             int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,5,opt,name=organizationCode,proto3" json:"organizationCode,omitempty"`
	SearchType       int32                  `protobuf:"varint,6,opt,name=searchType,proto3" json:"searchType,omitempty"`
	DepartmentCode   string                 `protobuf:"bytes,7,opt,name=departmentCode,proto3" json:"departmentCode,omitempty"`
	AccountCode      string                 `protobuf:"bytes,8,opt,name=accountCode,proto3" json:"accountCode,omitempty"`
	Authorize        string                 `protobuf:"bytes,9,opt,name=authorize,proto3" json:"authorize,omitempty"`
	IsOwner          int32                  `protobuf:"varint,10,opt,name=isOwner,proto3" json:"isOwner,omitempty"`
	Name             string                 `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Mobile           string                 `protobuf:"bytes,12,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email            string                 `protobuf:"bytes,13,opt,name=email,proto3" json:"email,omitempty"`
	Avatar           string                 `protobuf:"bytes,14,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Position         string                 `protobuf:"bytes,15,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountReqMessage) Reset() {
	*x = AccountReqMessage{}
	mi := &file_account_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountReqMessage) ProtoMessage() {}

func (x *AccountReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountReqMessage.ProtoReflect.Descriptor instead.
func (*AccountReqMessage) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{0}
}

func (x *AccountReqMessage) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *AccountReqMessage) GetProjectCode() string {
	if x != nil {
		return x.ProjectCode
	}
	return ""
}

func (x *AccountReqMessage) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AccountReqMessage) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AccountReqMessage) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *AccountReqMessage) GetSearchType() int32 {
	if x != nil {
		return x.SearchType
	}
	return 0
}

func (x *AccountReqMessage) GetDepartmentCode() string {
	if x != nil {
		return x.DepartmentCode
	}
	return ""
}

func (x *AccountReqMessage) GetAccountCode() string {
	if x != nil {
		return x.AccountCode
	}
	return ""
}

func (x *AccountReqMessage) GetAuthorize() string {
	if x != nil {
		return x.Authorize
	}
	return ""
}

func (x *AccountReqMessage) GetIsOwner() int32 {
	if x != nil {
		return x.IsOwner
	}
	return 0
}

func (x *AccountReqMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountReqMessage) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AccountReqMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountReqMessage) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AccountReqMessage) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

type MemberAccount struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code              string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	OrganizationCode  string                 `protobuf:"bytes,3,opt,name=OrganizationCode,proto3" json:"OrganizationCode,omitempty"`
	DepartmentCode    string                 `protobuf:"bytes,4,opt,name=DepartmentCode,proto3" json:"DepartmentCode,omitempty"`
	Authorize         string                 `protobuf:"bytes,5,opt,name=Authorize,proto3" json:"Authorize,omitempty"`
	IsOwner           int32                  `protobuf:"varint,6,opt,name=isOwner,proto3" json:"isOwner,omitempty"`
	Name              string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Mobile            string                 `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email             string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	CreateTime        string                 `protobuf:"bytes,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	LastLoginTime     string                 `protobuf:"bytes,11,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
	Status            int32                  `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	Description       string                 `protobuf:"bytes,13,opt,name=Description,proto3" json:"Description,omitempty"`
	Avatar            string                 `protobuf:"bytes,14,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Position          string                 `protobuf:"bytes,15,opt,name=Position,proto3" json:"Position,omitempty"`
	Department        string                 `protobuf:"bytes,16,opt,name=Department,proto3" json:"Department,omitempty"`
	MembarAccountCode string                 `protobuf:"bytes,17,opt,name=MembarAccountCode,proto3" json:"MembarAccountCode,omitempty"`
	Departments       string                 `protobuf:"bytes,18,opt,name=Departments,proto3" json:"Departments,omitempty"`
	StatusText        string                 `protobuf:"bytes,19,opt,name=StatusText,proto3" json:"StatusText,omitempty"`
	AuthorizeArr      []string               `protobuf:"bytes,20,rep,name=AuthorizeArr,proto3" json:"AuthorizeArr,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MemberAccount) Reset() {
	*x = MemberAccount{}
	mi := &file_account_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberAccount) ProtoMessage() {}

func (x *MemberAccount) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberAccount.ProtoReflect.Descriptor instead.
func (*MemberAccount) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{1}
}

func (x *MemberAccount) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberAccount) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MemberAccount) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *MemberAccount) GetDepartmentCode() string {
	if x != nil {
		return x.DepartmentCode
	}
	return ""
}

func (x *MemberAccount) GetAuthorize() string {
	if x != nil {
		return x.Authorize
	}
	return ""
}

func (x *MemberAccount) GetIsOwner() int32 {
	if x != nil {
		return x.IsOwner
	}
	return 0
}

func (x *MemberAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberAccount) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *MemberAccount) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MemberAccount) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *MemberAccount) GetLastLoginTime() string {
	if x != nil {
		return x.LastLoginTime
	}
	return ""
}

func (x *MemberAccount) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MemberAccount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MemberAccount) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *MemberAccount) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *MemberAccount) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *MemberAccount) GetMembarAccountCode() string {
	if x != nil {
		return x.MembarAccountCode
	}
	return ""
}

func (x *MemberAccount) GetDepartments() string {
	if x != nil {
		return x.Departments
	}
	return ""
}

func (x *MemberAccount) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *MemberAccount) GetAuthorizeArr() []string {
	if x != nil {
		return x.AuthorizeArr
	}
	return nil
}

type ProjectAuth struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,2,opt,name=OrganizationCode,proto3" json:"OrganizationCode,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	CreateAt         string                 `protobuf:"bytes,4,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	Sort             int32                  `protobuf:"varint,5,opt,name=Sort,proto3" json:"Sort,omitempty"`
	Status           int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Desc             string                 `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	CreateBy         int64                  `protobuf:"varint,8,opt,name=CreateBy,proto3" json:"CreateBy,omitempty"`
	IsDefault        int32                  `protobuf:"varint,9,opt,name=IsDefault,proto3" json:"IsDefault,omitempty"`
	Type             string                 `protobuf:"bytes,10,opt,name=Type,proto3" json:"Type,omitempty"`
	CanDelete        int32                  `protobuf:"varint,11,opt,name=CanDelete,proto3" json:"CanDelete,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProjectAuth) Reset() {
	*x = ProjectAuth{}
	mi := &file_account_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectAuth) ProtoMessage() {}

func (x *ProjectAuth) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectAuth.ProtoReflect.Descriptor instead.
func (*ProjectAuth) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectAuth) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectAuth) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *ProjectAuth) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProjectAuth) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *ProjectAuth) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProjectAuth) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProjectAuth) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ProjectAuth) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *ProjectAuth) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *ProjectAuth) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProjectAuth) GetCanDelete() int32 {
	if x != nil {
		return x.CanDelete
	}
	return 0
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	AccountList   []*MemberAccount `protobuf:"bytes,2,rep,name=accountList,proto3" json:"accountList,omitempty"`
	AuthList      []*ProjectAuth   `protobuf:"bytes,3,rep,name=authList,proto3" json:"authList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_account_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{3}
}

func (x *AccountResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AccountResponse) GetAccountList() []*MemberAccount {
	if x != nil {
		return x.AccountList
	}
	return nil
}

func (x *AccountResponse) GetAuthList() []*ProjectAuth {
	if x != nil {
		return x.AuthList
	}
	return nil
}

var File_account_service_proto protoreflect.FileDescriptor

const file_account_service_proto_rawDesc = "" +
	"\n" +
	"\x15account_service.proto\x12\x12account.service.v1\"\xa9\x03\n" +
	"\x11AccountReqMessage\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\x03R\bmemberId\x12 \n" +
	"\vprojectCode\x18\x02 \x01(\tR\vprojectCode\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\x12*\n" +
	"\x10organizationCode\x18\x05 \x01(\tR\x10organizationCode\x12\x1e\n" +
	"\n" +
	"searchType\x18\x06 \x01(\x05R\n" +
	"searchType\x12&\n" +
	"\x0edepartmentCode\x18\a \x01(\tR\x0edepartmentCode\x12 \n" +
	"\vaccountCode\x18\b \x01(\tR\vaccountCode\x12\x1c\n" +
	"\tauthorize\x18\t \x01(\tR\tauthorize\x12\x18\n" +
	"\aisOwner\x18\n" +
	" \x01(\x05R\aisOwner\x12\x12\n" +
	"\x04name\x18\v \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\f \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\r \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x0e \x01(\tR\x06avatar\"\xe9\x04\n" +
	"\rMemberAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12*\n" +
	"\x10OrganizationCode\x18\x03 \x01(\tR\x10OrganizationCode\x12&\n" +
	"\x0eDepartmentCode\x18\x04 \x01(\tR\x0eDepartmentCode\x12\x1c\n" +
	"\tAuthorize\x18\x05 \x01(\tR\tAuthorize\x12\x18\n" +
	"\aisOwner\x18\x06 \x01(\x05R\aisOwner\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\b \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x12\x1e\n" +
	"\n" +
	"createTime\x18\n" +
	" \x01(\tR\n" +
	"createTime\x12$\n" +
	"\rlastLoginTime\x18\v \x01(\tR\rlastLoginTime\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\x12 \n" +
	"\vDescription\x18\r \x01(\tR\vDescription\x12\x16\n" +
	"\x06Avatar\x18\x0e \x01(\tR\x06Avatar\x12\x1a\n" +
	"\bPosition\x18\x0f \x01(\tR\bPosition\x12\x1e\n" +
	"\n" +
	"Department\x18\x10 \x01(\tR\n" +
	"Department\x12,\n" +
	"\x11MembarAccountCode\x18\x11 \x01(\tR\x11MembarAccountCode\x12 \n" +
	"\vDepartments\x18\x12 \x01(\tR\vDepartments\x12\x1e\n" +
	"\n" +
	"StatusText\x18\x13 \x01(\tR\n" +
	"StatusText\x12\"\n" +
	"\fAuthorizeArr\x18\x14 \x03(\tR\fAuthorizeArr\"\xa7\x02\n" +
	"\vProjectAuth\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x10OrganizationCode\x18\x02 \x01(\tR\x10OrganizationCode\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x12\x1a\n" +
	"\bCreateAt\x18\x04 \x01(\tR\bCreateAt\x12\x12\n" +
	"\x04Sort\x18\x05 \x01(\x05R\x04Sort\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x12\n" +
	"\x04desc\x18\a \x01(\tR\x04desc\x12\x1a\n" +
	"\bCreateBy\x18\b \x01(\x03R\bCreateBy\x12\x1c\n" +
	"\tIsDefault\x18\t \x01(\x05R\tIsDefault\x12\x12\n" +
	"\x04Type\x18\n" +
	" \x01(\tR\x04Type\x12\x1c\n" +
	"\tCanDelete\x18\v \x01(\x05R\tCanDelete\"\xa9\x01\n" +
	"\x0fAccountResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12C\n" +
	"\vaccountList\x18\x02 \x03(\v2!.account.service.v1.MemberAccountR\vaccountList\x12;\n" +
	"\bauthList\x18\x03 \x03(\v2\x1f.account.service.v1.ProjectAuthR\bauthList2\xc6\x01\n" +
	"\x0eAccountService\x12W\n" +
	"\aAccount\x12%.account.service.v1.AccountReqMessage\x1a#.account.service.v1.AccountResponse\"\x00\x12[\n" +
	"\vSaveAccount\x12%.account.service.v1.AccountReqMessage\x1a#.account.service.v1.AccountResponse\"\x00B0Z.project-project/pkg/service/account.service.v1b\x06proto3"

var (
	file_account_service_proto_rawDescOnce sync.Once
	file_account_service_proto_rawDescData []byte
)

func file_account_service_proto_rawDescGZIP() []byte {
	file_account_service_proto_rawDescOnce.Do(func() {
		file_account_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_service_proto_rawDesc), len(file_account_service_proto_rawDesc)))
	})
	return file_account_service_proto_rawDescData
}

var file_account_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_account_service_proto_goTypes = []any{
	(*AccountReqMessage)(nil), // 0: account.service.v1.AccountReqMessage
	(*MemberAccount)(nil),     // 1: account.service.v1.MemberAccount
	(*ProjectAuth)(nil),       // 2: account.service.v1.ProjectAuth
	(*AccountResponse)(nil),   // 3: account.service.v1.AccountResponse
}
var file_account_service_proto_depIdxs = []int32{
	1, // 0: account.service.v1.AccountResponse.accountList:type_name -> account.service.v1.MemberAccount
	2, // 1: account.service.v1.AccountResponse.authList:type_name -> account.service.v1.ProjectAuth
	0, // 2: account.service.v1.AccountService.Account:input_type -> account.service.v1.AccountReqMessage
	0, // 3: account.service.v1.AccountService.SaveAccount:input_type -> account.service.v1.AccountReqMessage
	3, // 4: account.service.v1.AccountService.Account:output_type -> account.service.v1.AccountResponse
	3, // 5: account.service.v1.AccountService.SaveAccount:output_type -> account.service.v1.AccountResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_account_service_proto_init() }
func file_account_service_proto_init() {
	if File_account_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_service_proto_rawDesc), len(file_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_service_proto_goTypes,
		DependencyIndexes: file_account_service_proto_depIdxs,
		MessageInfos:      file_account_service_proto_msgTypes,
	}.Build()
	File_account_service_proto = out.File
	file_account_service_proto_goTypes = nil
	file_account_service_proto_depIdxs = nil
}
