server:
  name: "project-api"
  addr: "0.0.0.0:80"
zap:
  debugFileName: "/logs/debug/project-api-debug.log"
  infoFileName: "/logs/info/project-api-info.log"
  warnFileName: "/logs/error/project-api-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "etcd-node1:2379"
    - "etcd-node2:2379"
    - "etcd-node3:2379"
jaeger:
  endpoints: "http://localhost:14268/api/traces"
minio:
  endpoint: "minio:9000"
  accessKey: "admin"
  secretKey: "admin123456"
  bucket: "msproject"
  useSSL: false