// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: task_service.proto

package task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_TaskStages_FullMethodName          = "/task.service.v1.TaskService/TaskStages"
	TaskService_TaskStagesSort_FullMethodName      = "/task.service.v1.TaskService/TaskStagesSort"
	TaskService_MemberProjectList_FullMethodName   = "/task.service.v1.TaskService/MemberProjectList"
	TaskService_TaskList_FullMethodName            = "/task.service.v1.TaskService/TaskList"
	TaskService_SaveTask_FullMethodName            = "/task.service.v1.TaskService/SaveTask"
	TaskService_EditTask_FullMethodName            = "/task.service.v1.TaskService/EditTask"
	TaskService_TaskSort_FullMethodName            = "/task.service.v1.TaskService/TaskSort"
	TaskService_TaskDone_FullMethodName            = "/task.service.v1.TaskService/TaskDone"
	TaskService_MyTaskList_FullMethodName          = "/task.service.v1.TaskService/MyTaskList"
	TaskService_ReadTask_FullMethodName            = "/task.service.v1.TaskService/ReadTask"
	TaskService_ListTaskMember_FullMethodName      = "/task.service.v1.TaskService/ListTaskMember"
	TaskService_TaskLog_FullMethodName             = "/task.service.v1.TaskService/TaskLog"
	TaskService_TaskWorkTimeList_FullMethodName    = "/task.service.v1.TaskService/TaskWorkTimeList"
	TaskService_SaveTaskWorkTime_FullMethodName    = "/task.service.v1.TaskService/SaveTaskWorkTime"
	TaskService_SaveTaskFile_FullMethodName        = "/task.service.v1.TaskService/SaveTaskFile"
	TaskService_TaskSources_FullMethodName         = "/task.service.v1.TaskService/TaskSources"
	TaskService_CreateComment_FullMethodName       = "/task.service.v1.TaskService/CreateComment"
	TaskService_SaveTaskStages_FullMethodName      = "/task.service.v1.TaskService/SaveTaskStages"
	TaskService_EditTaskStages_FullMethodName      = "/task.service.v1.TaskService/EditTaskStages"
	TaskService_DeleteTaskStages_FullMethodName    = "/task.service.v1.TaskService/DeleteTaskStages"
	TaskService_FileIndex_FullMethodName           = "/task.service.v1.TaskService/FileIndex"
	TaskService_FileRead_FullMethodName            = "/task.service.v1.TaskService/FileRead"
	TaskService_FileEdit_FullMethodName            = "/task.service.v1.TaskService/FileEdit"
	TaskService_FileRecycle_FullMethodName         = "/task.service.v1.TaskService/FileRecycle"
	TaskService_FileRecovery_FullMethodName        = "/task.service.v1.TaskService/FileRecovery"
	TaskService_FileDelete_FullMethodName          = "/task.service.v1.TaskService/FileDelete"
	TaskService_TaskRecycle_FullMethodName         = "/task.service.v1.TaskService/TaskRecycle"
	TaskService_TaskDelete_FullMethodName          = "/task.service.v1.TaskService/TaskDelete"
	TaskService_TaskRecovery_FullMethodName        = "/task.service.v1.TaskService/TaskRecovery"
	TaskService_TaskTagList_FullMethodName         = "/task.service.v1.TaskService/TaskTagList"
	TaskService_SaveTaskTag_FullMethodName         = "/task.service.v1.TaskService/SaveTaskTag"
	TaskService_EditTaskTag_FullMethodName         = "/task.service.v1.TaskService/EditTaskTag"
	TaskService_DeleteTaskTag_FullMethodName       = "/task.service.v1.TaskService/DeleteTaskTag"
	TaskService_TaskToTags_FullMethodName          = "/task.service.v1.TaskService/TaskToTags"
	TaskService_SetTag_FullMethodName              = "/task.service.v1.TaskService/SetTag"
	TaskService_DelTaskWorkTime_FullMethodName     = "/task.service.v1.TaskService/DelTaskWorkTime"
	TaskService_TaskLike_FullMethodName            = "/task.service.v1.TaskService/TaskLike"
	TaskService_TaskStar_FullMethodName            = "/task.service.v1.TaskService/TaskStar"
	TaskService_SetPrivate_FullMethodName          = "/task.service.v1.TaskService/SetPrivate"
	TaskService_ProjectStats_FullMethodName        = "/task.service.v1.TaskService/ProjectStats"
	TaskService_ProjectReport_FullMethodName       = "/task.service.v1.TaskService/ProjectReport"
	TaskService_DateTotalForProject_FullMethodName = "/task.service.v1.TaskService/DateTotalForProject"
	TaskService_RecycleBatch_FullMethodName        = "/task.service.v1.TaskService/RecycleBatch"
	TaskService_BatchAssignTask_FullMethodName     = "/task.service.v1.TaskService/BatchAssignTask"
	TaskService_InviteMember_FullMethodName        = "/task.service.v1.TaskService/InviteMember"
	TaskService_InviteMemberBatch_FullMethodName   = "/task.service.v1.TaskService/InviteMemberBatch"
	TaskService_GetListByTaskTag_FullMethodName    = "/task.service.v1.TaskService/GetListByTaskTag"
	TaskService_DeleteSourceLink_FullMethodName    = "/task.service.v1.TaskService/DeleteSourceLink"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	TaskStages(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskStagesResponse, error)
	TaskStagesSort(ctx context.Context, in *TaskStagesSortReqMessage, opts ...grpc.CallOption) (*TaskStagesSortResponse, error)
	MemberProjectList(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*MemberProjectResponse, error)
	TaskList(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskListResponse, error)
	SaveTask(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskMessage, error)
	EditTask(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskMessage, error)
	TaskSort(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskSortResponse, error)
	TaskDone(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskSortResponse, error)
	MyTaskList(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*MyTaskListResponse, error)
	ReadTask(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskMessage, error)
	ListTaskMember(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskMemberList, error)
	TaskLog(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskLogList, error)
	TaskWorkTimeList(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskWorkTimeResponse, error)
	SaveTaskWorkTime(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*SaveTaskWorkTimeResponse, error)
	SaveTaskFile(ctx context.Context, in *TaskFileReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error)
	TaskSources(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskSourceResponse, error)
	CreateComment(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	SaveTaskStages(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskStagesResponse, error)
	EditTaskStages(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskStagesResponse, error)
	DeleteTaskStages(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskStagesResponse, error)
	FileIndex(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileListResponse, error)
	FileRead(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error)
	FileEdit(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error)
	FileRecycle(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error)
	FileRecovery(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error)
	FileDelete(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error)
	TaskRecycle(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskRecycleResponse, error)
	TaskDelete(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskDeleteResponse, error)
	TaskRecovery(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskRecoveryResponse, error)
	TaskTagList(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskTagListResponse, error)
	SaveTaskTag(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskTagResponse, error)
	EditTaskTag(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskTagResponse, error)
	DeleteTaskTag(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*DeleteTaskTagResponse, error)
	TaskToTags(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskToTagsResponse, error)
	SetTag(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error)
	DelTaskWorkTime(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error)
	TaskLike(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error)
	TaskStar(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error)
	SetPrivate(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error)
	ProjectStats(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*ProjectStatsResponse, error)
	ProjectReport(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*ProjectReportResponse, error)
	DateTotalForProject(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*DateTotalListResponse, error)
	RecycleBatch(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error)
	BatchAssignTask(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error)
	InviteMember(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error)
	InviteMemberBatch(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error)
	GetListByTaskTag(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskListResponse, error)
	DeleteSourceLink(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) TaskStages(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskStagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStagesResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskStages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskStagesSort(ctx context.Context, in *TaskStagesSortReqMessage, opts ...grpc.CallOption) (*TaskStagesSortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStagesSortResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskStagesSort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) MemberProjectList(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*MemberProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberProjectResponse)
	err := c.cc.Invoke(ctx, TaskService_MemberProjectList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskList(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskListResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SaveTask(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskMessage)
	err := c.cc.Invoke(ctx, TaskService_SaveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) EditTask(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskMessage)
	err := c.cc.Invoke(ctx, TaskService_EditTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskSort(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskSortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskSortResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskSort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskDone(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskSortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskSortResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskDone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) MyTaskList(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*MyTaskListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MyTaskListResponse)
	err := c.cc.Invoke(ctx, TaskService_MyTaskList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ReadTask(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskMessage)
	err := c.cc.Invoke(ctx, TaskService_ReadTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTaskMember(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskMemberList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskMemberList)
	err := c.cc.Invoke(ctx, TaskService_ListTaskMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskLog(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskLogList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskLogList)
	err := c.cc.Invoke(ctx, TaskService_TaskLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskWorkTimeList(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskWorkTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskWorkTimeResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskWorkTimeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SaveTaskWorkTime(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*SaveTaskWorkTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveTaskWorkTimeResponse)
	err := c.cc.Invoke(ctx, TaskService_SaveTaskWorkTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SaveTaskFile(ctx context.Context, in *TaskFileReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskFileResponse)
	err := c.cc.Invoke(ctx, TaskService_SaveTaskFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskSources(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskSourceResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CreateComment(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, TaskService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SaveTaskStages(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskStagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStagesResponse)
	err := c.cc.Invoke(ctx, TaskService_SaveTaskStages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) EditTaskStages(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskStagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStagesResponse)
	err := c.cc.Invoke(ctx, TaskService_EditTaskStages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTaskStages(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskStagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStagesResponse)
	err := c.cc.Invoke(ctx, TaskService_DeleteTaskStages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) FileIndex(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskFileListResponse)
	err := c.cc.Invoke(ctx, TaskService_FileIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) FileRead(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskFileResponse)
	err := c.cc.Invoke(ctx, TaskService_FileRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) FileEdit(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskFileResponse)
	err := c.cc.Invoke(ctx, TaskService_FileEdit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) FileRecycle(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskFileResponse)
	err := c.cc.Invoke(ctx, TaskService_FileRecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) FileRecovery(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskFileResponse)
	err := c.cc.Invoke(ctx, TaskService_FileRecovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) FileDelete(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskFileResponse)
	err := c.cc.Invoke(ctx, TaskService_FileDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskRecycle(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskRecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskRecycleResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskRecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskDelete(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskDeleteResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskRecovery(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskRecoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskRecoveryResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskRecovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskTagList(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskTagListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskTagListResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskTagList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SaveTaskTag(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskTagResponse)
	err := c.cc.Invoke(ctx, TaskService_SaveTaskTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) EditTaskTag(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskTagResponse)
	err := c.cc.Invoke(ctx, TaskService_EditTaskTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTaskTag(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*DeleteTaskTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskTagResponse)
	err := c.cc.Invoke(ctx, TaskService_DeleteTaskTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskToTags(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskToTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskToTagsResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskToTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SetTag(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonBoolResponse)
	err := c.cc.Invoke(ctx, TaskService_SetTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DelTaskWorkTime(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonBoolResponse)
	err := c.cc.Invoke(ctx, TaskService_DelTaskWorkTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskLike(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonBoolResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TaskStar(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonBoolResponse)
	err := c.cc.Invoke(ctx, TaskService_TaskStar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SetPrivate(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonBoolResponse)
	err := c.cc.Invoke(ctx, TaskService_SetPrivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ProjectStats(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*ProjectStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectStatsResponse)
	err := c.cc.Invoke(ctx, TaskService_ProjectStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ProjectReport(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*ProjectReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectReportResponse)
	err := c.cc.Invoke(ctx, TaskService_ProjectReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DateTotalForProject(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*DateTotalListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DateTotalListResponse)
	err := c.cc.Invoke(ctx, TaskService_DateTotalForProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) RecycleBatch(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonBoolResponse)
	err := c.cc.Invoke(ctx, TaskService_RecycleBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) BatchAssignTask(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonBoolResponse)
	err := c.cc.Invoke(ctx, TaskService_BatchAssignTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) InviteMember(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonBoolResponse)
	err := c.cc.Invoke(ctx, TaskService_InviteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) InviteMemberBatch(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonBoolResponse)
	err := c.cc.Invoke(ctx, TaskService_InviteMemberBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetListByTaskTag(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*TaskListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskListResponse)
	err := c.cc.Invoke(ctx, TaskService_GetListByTaskTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteSourceLink(ctx context.Context, in *TaskReqMessage, opts ...grpc.CallOption) (*CommonBoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonBoolResponse)
	err := c.cc.Invoke(ctx, TaskService_DeleteSourceLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
type TaskServiceServer interface {
	TaskStages(context.Context, *TaskReqMessage) (*TaskStagesResponse, error)
	TaskStagesSort(context.Context, *TaskStagesSortReqMessage) (*TaskStagesSortResponse, error)
	MemberProjectList(context.Context, *TaskReqMessage) (*MemberProjectResponse, error)
	TaskList(context.Context, *TaskReqMessage) (*TaskListResponse, error)
	SaveTask(context.Context, *TaskReqMessage) (*TaskMessage, error)
	EditTask(context.Context, *TaskReqMessage) (*TaskMessage, error)
	TaskSort(context.Context, *TaskReqMessage) (*TaskSortResponse, error)
	TaskDone(context.Context, *TaskReqMessage) (*TaskSortResponse, error)
	MyTaskList(context.Context, *TaskReqMessage) (*MyTaskListResponse, error)
	ReadTask(context.Context, *TaskReqMessage) (*TaskMessage, error)
	ListTaskMember(context.Context, *TaskReqMessage) (*TaskMemberList, error)
	TaskLog(context.Context, *TaskReqMessage) (*TaskLogList, error)
	TaskWorkTimeList(context.Context, *TaskReqMessage) (*TaskWorkTimeResponse, error)
	SaveTaskWorkTime(context.Context, *TaskReqMessage) (*SaveTaskWorkTimeResponse, error)
	SaveTaskFile(context.Context, *TaskFileReqMessage) (*TaskFileResponse, error)
	TaskSources(context.Context, *TaskReqMessage) (*TaskSourceResponse, error)
	CreateComment(context.Context, *TaskReqMessage) (*CreateCommentResponse, error)
	SaveTaskStages(context.Context, *TaskReqMessage) (*TaskStagesResponse, error)
	EditTaskStages(context.Context, *TaskReqMessage) (*TaskStagesResponse, error)
	DeleteTaskStages(context.Context, *TaskReqMessage) (*TaskStagesResponse, error)
	FileIndex(context.Context, *TaskReqMessage) (*TaskFileListResponse, error)
	FileRead(context.Context, *TaskReqMessage) (*TaskFileResponse, error)
	FileEdit(context.Context, *TaskReqMessage) (*TaskFileResponse, error)
	FileRecycle(context.Context, *TaskReqMessage) (*TaskFileResponse, error)
	FileRecovery(context.Context, *TaskReqMessage) (*TaskFileResponse, error)
	FileDelete(context.Context, *TaskReqMessage) (*TaskFileResponse, error)
	TaskRecycle(context.Context, *TaskReqMessage) (*TaskRecycleResponse, error)
	TaskDelete(context.Context, *TaskReqMessage) (*TaskDeleteResponse, error)
	TaskRecovery(context.Context, *TaskReqMessage) (*TaskRecoveryResponse, error)
	TaskTagList(context.Context, *TaskReqMessage) (*TaskTagListResponse, error)
	SaveTaskTag(context.Context, *TaskReqMessage) (*TaskTagResponse, error)
	EditTaskTag(context.Context, *TaskReqMessage) (*TaskTagResponse, error)
	DeleteTaskTag(context.Context, *TaskReqMessage) (*DeleteTaskTagResponse, error)
	TaskToTags(context.Context, *TaskReqMessage) (*TaskToTagsResponse, error)
	SetTag(context.Context, *TaskReqMessage) (*CommonBoolResponse, error)
	DelTaskWorkTime(context.Context, *TaskReqMessage) (*CommonBoolResponse, error)
	TaskLike(context.Context, *TaskReqMessage) (*CommonBoolResponse, error)
	TaskStar(context.Context, *TaskReqMessage) (*CommonBoolResponse, error)
	SetPrivate(context.Context, *TaskReqMessage) (*CommonBoolResponse, error)
	ProjectStats(context.Context, *TaskReqMessage) (*ProjectStatsResponse, error)
	ProjectReport(context.Context, *TaskReqMessage) (*ProjectReportResponse, error)
	DateTotalForProject(context.Context, *TaskReqMessage) (*DateTotalListResponse, error)
	RecycleBatch(context.Context, *TaskReqMessage) (*CommonBoolResponse, error)
	BatchAssignTask(context.Context, *TaskReqMessage) (*CommonBoolResponse, error)
	InviteMember(context.Context, *TaskReqMessage) (*CommonBoolResponse, error)
	InviteMemberBatch(context.Context, *TaskReqMessage) (*CommonBoolResponse, error)
	GetListByTaskTag(context.Context, *TaskReqMessage) (*TaskListResponse, error)
	DeleteSourceLink(context.Context, *TaskReqMessage) (*CommonBoolResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) TaskStages(context.Context, *TaskReqMessage) (*TaskStagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskStages not implemented")
}
func (UnimplementedTaskServiceServer) TaskStagesSort(context.Context, *TaskStagesSortReqMessage) (*TaskStagesSortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskStagesSort not implemented")
}
func (UnimplementedTaskServiceServer) MemberProjectList(context.Context, *TaskReqMessage) (*MemberProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MemberProjectList not implemented")
}
func (UnimplementedTaskServiceServer) TaskList(context.Context, *TaskReqMessage) (*TaskListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskList not implemented")
}
func (UnimplementedTaskServiceServer) SaveTask(context.Context, *TaskReqMessage) (*TaskMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTask not implemented")
}
func (UnimplementedTaskServiceServer) EditTask(context.Context, *TaskReqMessage) (*TaskMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTask not implemented")
}
func (UnimplementedTaskServiceServer) TaskSort(context.Context, *TaskReqMessage) (*TaskSortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskSort not implemented")
}
func (UnimplementedTaskServiceServer) TaskDone(context.Context, *TaskReqMessage) (*TaskSortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskDone not implemented")
}
func (UnimplementedTaskServiceServer) MyTaskList(context.Context, *TaskReqMessage) (*MyTaskListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MyTaskList not implemented")
}
func (UnimplementedTaskServiceServer) ReadTask(context.Context, *TaskReqMessage) (*TaskMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTask not implemented")
}
func (UnimplementedTaskServiceServer) ListTaskMember(context.Context, *TaskReqMessage) (*TaskMemberList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTaskMember not implemented")
}
func (UnimplementedTaskServiceServer) TaskLog(context.Context, *TaskReqMessage) (*TaskLogList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskLog not implemented")
}
func (UnimplementedTaskServiceServer) TaskWorkTimeList(context.Context, *TaskReqMessage) (*TaskWorkTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskWorkTimeList not implemented")
}
func (UnimplementedTaskServiceServer) SaveTaskWorkTime(context.Context, *TaskReqMessage) (*SaveTaskWorkTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTaskWorkTime not implemented")
}
func (UnimplementedTaskServiceServer) SaveTaskFile(context.Context, *TaskFileReqMessage) (*TaskFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTaskFile not implemented")
}
func (UnimplementedTaskServiceServer) TaskSources(context.Context, *TaskReqMessage) (*TaskSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskSources not implemented")
}
func (UnimplementedTaskServiceServer) CreateComment(context.Context, *TaskReqMessage) (*CreateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedTaskServiceServer) SaveTaskStages(context.Context, *TaskReqMessage) (*TaskStagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTaskStages not implemented")
}
func (UnimplementedTaskServiceServer) EditTaskStages(context.Context, *TaskReqMessage) (*TaskStagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTaskStages not implemented")
}
func (UnimplementedTaskServiceServer) DeleteTaskStages(context.Context, *TaskReqMessage) (*TaskStagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTaskStages not implemented")
}
func (UnimplementedTaskServiceServer) FileIndex(context.Context, *TaskReqMessage) (*TaskFileListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileIndex not implemented")
}
func (UnimplementedTaskServiceServer) FileRead(context.Context, *TaskReqMessage) (*TaskFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRead not implemented")
}
func (UnimplementedTaskServiceServer) FileEdit(context.Context, *TaskReqMessage) (*TaskFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileEdit not implemented")
}
func (UnimplementedTaskServiceServer) FileRecycle(context.Context, *TaskReqMessage) (*TaskFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRecycle not implemented")
}
func (UnimplementedTaskServiceServer) FileRecovery(context.Context, *TaskReqMessage) (*TaskFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRecovery not implemented")
}
func (UnimplementedTaskServiceServer) FileDelete(context.Context, *TaskReqMessage) (*TaskFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileDelete not implemented")
}
func (UnimplementedTaskServiceServer) TaskRecycle(context.Context, *TaskReqMessage) (*TaskRecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskRecycle not implemented")
}
func (UnimplementedTaskServiceServer) TaskDelete(context.Context, *TaskReqMessage) (*TaskDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskDelete not implemented")
}
func (UnimplementedTaskServiceServer) TaskRecovery(context.Context, *TaskReqMessage) (*TaskRecoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskRecovery not implemented")
}
func (UnimplementedTaskServiceServer) TaskTagList(context.Context, *TaskReqMessage) (*TaskTagListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskTagList not implemented")
}
func (UnimplementedTaskServiceServer) SaveTaskTag(context.Context, *TaskReqMessage) (*TaskTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTaskTag not implemented")
}
func (UnimplementedTaskServiceServer) EditTaskTag(context.Context, *TaskReqMessage) (*TaskTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTaskTag not implemented")
}
func (UnimplementedTaskServiceServer) DeleteTaskTag(context.Context, *TaskReqMessage) (*DeleteTaskTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTaskTag not implemented")
}
func (UnimplementedTaskServiceServer) TaskToTags(context.Context, *TaskReqMessage) (*TaskToTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskToTags not implemented")
}
func (UnimplementedTaskServiceServer) SetTag(context.Context, *TaskReqMessage) (*CommonBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTag not implemented")
}
func (UnimplementedTaskServiceServer) DelTaskWorkTime(context.Context, *TaskReqMessage) (*CommonBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelTaskWorkTime not implemented")
}
func (UnimplementedTaskServiceServer) TaskLike(context.Context, *TaskReqMessage) (*CommonBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskLike not implemented")
}
func (UnimplementedTaskServiceServer) TaskStar(context.Context, *TaskReqMessage) (*CommonBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskStar not implemented")
}
func (UnimplementedTaskServiceServer) SetPrivate(context.Context, *TaskReqMessage) (*CommonBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPrivate not implemented")
}
func (UnimplementedTaskServiceServer) ProjectStats(context.Context, *TaskReqMessage) (*ProjectStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProjectStats not implemented")
}
func (UnimplementedTaskServiceServer) ProjectReport(context.Context, *TaskReqMessage) (*ProjectReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProjectReport not implemented")
}
func (UnimplementedTaskServiceServer) DateTotalForProject(context.Context, *TaskReqMessage) (*DateTotalListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DateTotalForProject not implemented")
}
func (UnimplementedTaskServiceServer) RecycleBatch(context.Context, *TaskReqMessage) (*CommonBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecycleBatch not implemented")
}
func (UnimplementedTaskServiceServer) BatchAssignTask(context.Context, *TaskReqMessage) (*CommonBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchAssignTask not implemented")
}
func (UnimplementedTaskServiceServer) InviteMember(context.Context, *TaskReqMessage) (*CommonBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteMember not implemented")
}
func (UnimplementedTaskServiceServer) InviteMemberBatch(context.Context, *TaskReqMessage) (*CommonBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteMemberBatch not implemented")
}
func (UnimplementedTaskServiceServer) GetListByTaskTag(context.Context, *TaskReqMessage) (*TaskListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListByTaskTag not implemented")
}
func (UnimplementedTaskServiceServer) DeleteSourceLink(context.Context, *TaskReqMessage) (*CommonBoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSourceLink not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call pancis, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_TaskStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskStages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskStages(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskStagesSort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStagesSortReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskStagesSort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskStagesSort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskStagesSort(ctx, req.(*TaskStagesSortReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_MemberProjectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).MemberProjectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_MemberProjectList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).MemberProjectList(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskList(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SaveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SaveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SaveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SaveTask(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_EditTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).EditTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_EditTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).EditTask(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskSort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskSort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskSort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskSort(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskDone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskDone(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_MyTaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).MyTaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_MyTaskList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).MyTaskList(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ReadTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ReadTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ReadTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ReadTask(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListTaskMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListTaskMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListTaskMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTaskMember(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskLog(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskWorkTimeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskWorkTimeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskWorkTimeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskWorkTimeList(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SaveTaskWorkTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SaveTaskWorkTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SaveTaskWorkTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SaveTaskWorkTime(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SaveTaskFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskFileReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SaveTaskFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SaveTaskFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SaveTaskFile(ctx, req.(*TaskFileReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskSources(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateComment(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SaveTaskStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SaveTaskStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SaveTaskStages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SaveTaskStages(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_EditTaskStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).EditTaskStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_EditTaskStages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).EditTaskStages(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTaskStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTaskStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeleteTaskStages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTaskStages(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_FileIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).FileIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_FileIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).FileIndex(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_FileRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).FileRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_FileRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).FileRead(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_FileEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).FileEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_FileEdit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).FileEdit(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_FileRecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).FileRecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_FileRecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).FileRecycle(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_FileRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).FileRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_FileRecovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).FileRecovery(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_FileDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).FileDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_FileDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).FileDelete(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskRecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskRecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskRecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskRecycle(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskDelete(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskRecovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskRecovery(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskTagList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskTagList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskTagList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskTagList(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SaveTaskTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SaveTaskTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SaveTaskTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SaveTaskTag(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_EditTaskTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).EditTaskTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_EditTaskTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).EditTaskTag(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTaskTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTaskTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeleteTaskTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTaskTag(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskToTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskToTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskToTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskToTags(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SetTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SetTag(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DelTaskWorkTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DelTaskWorkTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DelTaskWorkTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DelTaskWorkTime(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskLike(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TaskStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TaskStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TaskStar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TaskStar(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SetPrivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SetPrivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SetPrivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SetPrivate(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ProjectStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ProjectStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ProjectStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ProjectStats(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ProjectReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ProjectReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ProjectReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ProjectReport(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DateTotalForProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DateTotalForProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DateTotalForProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DateTotalForProject(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_RecycleBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).RecycleBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_RecycleBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).RecycleBatch(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_BatchAssignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).BatchAssignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_BatchAssignTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).BatchAssignTask(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_InviteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).InviteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_InviteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).InviteMember(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_InviteMemberBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).InviteMemberBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_InviteMemberBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).InviteMemberBatch(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetListByTaskTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetListByTaskTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetListByTaskTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetListByTaskTag(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteSourceLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteSourceLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeleteSourceLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteSourceLink(ctx, req.(*TaskReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.service.v1.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TaskStages",
			Handler:    _TaskService_TaskStages_Handler,
		},
		{
			MethodName: "TaskStagesSort",
			Handler:    _TaskService_TaskStagesSort_Handler,
		},
		{
			MethodName: "MemberProjectList",
			Handler:    _TaskService_MemberProjectList_Handler,
		},
		{
			MethodName: "TaskList",
			Handler:    _TaskService_TaskList_Handler,
		},
		{
			MethodName: "SaveTask",
			Handler:    _TaskService_SaveTask_Handler,
		},
		{
			MethodName: "EditTask",
			Handler:    _TaskService_EditTask_Handler,
		},
		{
			MethodName: "TaskSort",
			Handler:    _TaskService_TaskSort_Handler,
		},
		{
			MethodName: "TaskDone",
			Handler:    _TaskService_TaskDone_Handler,
		},
		{
			MethodName: "MyTaskList",
			Handler:    _TaskService_MyTaskList_Handler,
		},
		{
			MethodName: "ReadTask",
			Handler:    _TaskService_ReadTask_Handler,
		},
		{
			MethodName: "ListTaskMember",
			Handler:    _TaskService_ListTaskMember_Handler,
		},
		{
			MethodName: "TaskLog",
			Handler:    _TaskService_TaskLog_Handler,
		},
		{
			MethodName: "TaskWorkTimeList",
			Handler:    _TaskService_TaskWorkTimeList_Handler,
		},
		{
			MethodName: "SaveTaskWorkTime",
			Handler:    _TaskService_SaveTaskWorkTime_Handler,
		},
		{
			MethodName: "SaveTaskFile",
			Handler:    _TaskService_SaveTaskFile_Handler,
		},
		{
			MethodName: "TaskSources",
			Handler:    _TaskService_TaskSources_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _TaskService_CreateComment_Handler,
		},
		{
			MethodName: "SaveTaskStages",
			Handler:    _TaskService_SaveTaskStages_Handler,
		},
		{
			MethodName: "EditTaskStages",
			Handler:    _TaskService_EditTaskStages_Handler,
		},
		{
			MethodName: "DeleteTaskStages",
			Handler:    _TaskService_DeleteTaskStages_Handler,
		},
		{
			MethodName: "FileIndex",
			Handler:    _TaskService_FileIndex_Handler,
		},
		{
			MethodName: "FileRead",
			Handler:    _TaskService_FileRead_Handler,
		},
		{
			MethodName: "FileEdit",
			Handler:    _TaskService_FileEdit_Handler,
		},
		{
			MethodName: "FileRecycle",
			Handler:    _TaskService_FileRecycle_Handler,
		},
		{
			MethodName: "FileRecovery",
			Handler:    _TaskService_FileRecovery_Handler,
		},
		{
			MethodName: "FileDelete",
			Handler:    _TaskService_FileDelete_Handler,
		},
		{
			MethodName: "TaskRecycle",
			Handler:    _TaskService_TaskRecycle_Handler,
		},
		{
			MethodName: "TaskDelete",
			Handler:    _TaskService_TaskDelete_Handler,
		},
		{
			MethodName: "TaskRecovery",
			Handler:    _TaskService_TaskRecovery_Handler,
		},
		{
			MethodName: "TaskTagList",
			Handler:    _TaskService_TaskTagList_Handler,
		},
		{
			MethodName: "SaveTaskTag",
			Handler:    _TaskService_SaveTaskTag_Handler,
		},
		{
			MethodName: "EditTaskTag",
			Handler:    _TaskService_EditTaskTag_Handler,
		},
		{
			MethodName: "DeleteTaskTag",
			Handler:    _TaskService_DeleteTaskTag_Handler,
		},
		{
			MethodName: "TaskToTags",
			Handler:    _TaskService_TaskToTags_Handler,
		},
		{
			MethodName: "SetTag",
			Handler:    _TaskService_SetTag_Handler,
		},
		{
			MethodName: "DelTaskWorkTime",
			Handler:    _TaskService_DelTaskWorkTime_Handler,
		},
		{
			MethodName: "TaskLike",
			Handler:    _TaskService_TaskLike_Handler,
		},
		{
			MethodName: "TaskStar",
			Handler:    _TaskService_TaskStar_Handler,
		},
		{
			MethodName: "SetPrivate",
			Handler:    _TaskService_SetPrivate_Handler,
		},
		{
			MethodName: "ProjectStats",
			Handler:    _TaskService_ProjectStats_Handler,
		},
		{
			MethodName: "ProjectReport",
			Handler:    _TaskService_ProjectReport_Handler,
		},
		{
			MethodName: "DateTotalForProject",
			Handler:    _TaskService_DateTotalForProject_Handler,
		},
		{
			MethodName: "RecycleBatch",
			Handler:    _TaskService_RecycleBatch_Handler,
		},
		{
			MethodName: "BatchAssignTask",
			Handler:    _TaskService_BatchAssignTask_Handler,
		},
		{
			MethodName: "InviteMember",
			Handler:    _TaskService_InviteMember_Handler,
		},
		{
			MethodName: "InviteMemberBatch",
			Handler:    _TaskService_InviteMemberBatch_Handler,
		},
		{
			MethodName: "GetListByTaskTag",
			Handler:    _TaskService_GetListByTaskTag_Handler,
		},
		{
			MethodName: "DeleteSourceLink",
			Handler:    _TaskService_DeleteSourceLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task_service.proto",
}
